baseURL = "https://www.aiana.fr/"
languageCode = "fr"
title = "Aiana, un lecteur vidéo accessible adapté aux MOOC"
description = "Aiana vise à favoriser l’accès aux systèmes numériques d’enseignement et de formation sans exclure les personnes en situation de handicap notamment d’origine cognitif."
enableRobotsTXT = true
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]

pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  logo = "/img/aiana.jpg"
  description = "Aiana media player description"

[permalinks]
  post = "/:year/:slug/"
