baseURL = "https://www.aiana.fr/"
languageCode = "fr"
title = "Aiana, un lecteur web multimédia accessible adapté aux MOOC"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS"]
googleAnalytics = "UA-129183064-1"
removePathAccents = true

pygmentsUseClasses = true
pygmentsCodeFences = true

[params]
  logo = "/img/aiana.jpg"
  description = "Aiana vise à favoriser l’accès aux systèmes numériques d’enseignement et de formation sans exclure les personnes en situation de handicap notamment d’origine cognitif."

[permalinks]
  post = "/:year/:slug/"
